#!/bin/sh

format="$1"
container="$2"

if [ "${format}" = "" ]; then
    kubectl describe pod ${container}
    exit 0
fi

if [ "${format}" = '{{.NetworkSettings.IPAddress}}' ]; then
    kubectl get pod \
            --no-headers \
            --output=custom-columns=ADDRESS:.status.podIP \
            ${container}
    exit 0
fi

if [ "${format}" = '{ "machine" : "{{.Config.Labels.machine}}", "reqid" : "{{.Config.Labels.reqid}}", "instance_id" : "{{.Id}}" }' ]; then
    out=$(kubectl get pod \
          --output=jsonpath='"machine" : "{.metadata.labels.machine}", "reqid" : "{.metadata.labels.reqid}", "instance_id" : "{.metadata.name}"' \
          ${container})
    echo "{ ${out} }"
    exit 0
fi

echo "This format is not implemented in docker-hook (${format})"
exit 1
