#!/bin/bash

format="$1"
container="$(echo ${2//+/-})"

if [ "${format}" = "" ]; then
    kubectl describe pod ${container}
    exit 0
fi

if [ "${format}" = '{{.NetworkSettings.IPAddress}}' ]; then
    kubectl get pod \
            --no-headers \
            --output=custom-columns=ADDRESS:.status.podIP \
            ${container}
    exit 0
fi

if [ "${format}" = '{ "machine" : "{{.Config.Labels.machine}}", "reqid" : "{{.Config.Labels.reqid}}", "instance_id" : "{{.Id}}" }' ]; then
    out=$(kubectl get pod \
          --output=jsonpath='{.metadata.labels.machine} {.metadata.labels.reqid} {.metadata.name}' \
          ${container})
    stringarray=($out)
    echo "{ \"machine\" : \"${stringarray[0]}\", \"reqid\" : \"${stringarray[1]}\", \"instance_id\" : \"${stringarray[2]//-/+}\" }"
    exit 0
fi

echo "This format is not implemented in docker-hook (${format})"
exit 1
