#!/bin/bash
set -e

containers=$(kubectl get pod \
                     --no-headers \
                     --output custom-columns=NAME:.metadata.name \
                     "$@" | xargs)

for container in ${containers}; do
    echo "${container//-/+}"
done
