#!/bin/bash

container="$(echo ${1//___/-})"
job_name="${container%-*}"
grace_period="${2:-10}"
blocking=false

inverted_retry() {
    local max_attempts=${ATTEMPTS-50}
    local delay=${DELAY-10}
    local attempt=0
    local exitCode=0

    while [ $attempt -lt $max_attempts ]; do
        "$@" >/dev/null 2>&1
        exitCode=$?
        test $exitCode -eq 1 && break
        sleep $delay
        attempt=$(( attempt + 1 ))
    done

    return $exitCode
}

kubectl delete job \
        --grace-period=${grace_period} \
        ${job_name} >/dev/null 2>&1
test ! $? -eq 0 && exit 1

# block until resource gone (slow)
if ${blocking}; then
    inverted_retry kubectl get pod ${container}
    test ! $? -eq 1 && exit 1
fi

echo ${1}
