#!/bin/bash

pod_name="$(echo ${1//___/-})"
grace_period="${2:-10}"
blocking=false

retry() {
    local max_attempts=${ATTEMPTS-50}
    local delay=${DELAY-10}
    local attempt=0
    local expectedExitCode=$1
    shift
    local exitCode=$expectedExitCode

    while [ $attempt -lt $max_attempts ]; do
        "$@" >/dev/null 2>&1
        exitCode=$?
        test $exitCode -eq $expectedExitCode && break
        sleep $delay
        attempt=$(( attempt + 1 ))
    done

    return $exitCode
}

with_retry() {
    retry 0 "$@"
}
with_inverted_retry() {
    retry 1 "$@"
}

# block until resource gone (slow)
if ${blocking}; then
    ATTEMPTS=3 DELAY=60 with_retry kubectl delete pod \
            --grace-period=${grace_period} \
            ${pod_name} >/dev/null 2>&1
    test ! $? -eq 0 && exit 1

    ATTEMPTS=50 DELAY=10 with_inverted_retry kubectl get pod ${pod_name}
    test ! $? -eq 1 && exit 1
else
    ATTEMPTS=3 DELAY=60 with_retry kubectl delete pod \
            --grace-period=${grace_period} \
            ${pod_name} >/dev/null 2>&1
fi

echo ${1}
