version: '3'

services:
  frontend:
    build: .
    ports:
      - "${EXTERNAL_HTTP_PORT-8999}:8999"
    depends_on:
      - db
      - crossbar
    env_file: "${ENV_FILE-env}"
    environment:
      MASTER_MODE: frontend
      DB_URL: "mysql://eve:4m4zing@db:3306/buildbot_db?max_idle=300"
      WAMP_ROUTER_URL: 'ws://crossbar:10990/ws'

  backend:
    build: .
    ports:
      - "${EXTERNAL_PB_PORT-9999}:9999"
    depends_on:
      - db
      - crossbar
      - gitcache
    env_file: "${ENV_FILE-env}"
    environment:
      MASTER_MODE: backend
      DB_URL: "mysql://eve:4m4zing@db:3306/buildbot_db?max_idle=300"
      WAMP_ROUTER_URL: 'ws://crossbar:10990/ws'
      EXTERNAL_PB_PORT: ${EXTERNAL_PB_PORT-9999}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=4m4zingroot
      - MYSQL_DATABASE=buildbot_db
      - MYSQL_USER=eve
      - MYSQL_PASSWORD=4m4zing

  crossbar:
    image: crossbario/crossbar
    restart: always
    volumes:
      - ./tests/util/crossbar/crossbar.json:/node/.crossbar/config.json

  gitcache:
    build: eve/services/gitcache
    env_file: "${ENV_FILE-env}"
