version: '3'

services:
  frontend:
    build: .
    ports:
      - "${EXTERNAL_HTTP_PORT-8999}:8999"
    depends_on:
      - db
      - crossbar
    env_file: "${ENV_FILE-env}"
    environment:
      MASTER_MODE: frontend
      DB_URL: "mysql://eve:4m4zing@db:3306/buildbot_db?max_idle=300"
      WAMP_ROUTER_URL: 'ws://crossbar:10990/ws'

  backend:
    build: .
    ports:
      - "${EXTERNAL_PB_PORT-9999}:9999"
    depends_on:
      - db
      - crossbar
      - git_cache
    env_file: "${ENV_FILE-env}"
    environment:
      MASTER_MODE: backend
      DB_URL: "mysql://eve:4m4zing@db:3306/buildbot_db?max_idle=300"
      WAMP_ROUTER_URL: 'ws://crossbar:10990/ws'
      GIT_CACHE_PORT: 80
      GIT_CACHE_HOST: git_cache
      EXTERNAL_PB_PORT: ${EXTERNAL_PB_PORT-9999}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql/mysql-server:5.7
    restart: always
    env_file: "${ENV_FILE-env}"

  crossbar:
    image: crossbario/crossbar
    restart: always
    volumes:
      - ./tests/system/factories/crossbar.json:/node/.crossbar/config.json

  git_cache:
    build: src/eve/services/git_cache
    ports:
      - "${EXTERNAL_GIT_CACHE_PORT-8888}:80"
    env_file: "${ENV_FILE-env}"