# Default values file for eve-doc helm chart.

## nameOverride allows to change the name of the release
## rather than default value 'eve-doc'
nameOverride: "eve-doc"

## useShortName shorten names of Kubernetes resources.
##
##   The release name will not be included in fullname. This
##   is safe to use only if one release only is deployed
##
useShortNames: false

image:
  ## regitry to pull from.
  ##
  registry: docker.io

  ## repository on the registry to pull from.
  ##
  repository: scality/eve-doc

  ## tag specifies the version to deploy.
  ##
  tag: 1.3.45

  ## pullPolicy specifies the image pull policy
  ##
  ##   Defaults to 'IfNotPresent'
  ##
  pullPolicy: IfNotPresent

  ## pullsecrets specifies a list of imagePullSecrets.
  ##
  ##   Secrets must be manually created in the namespace.
  ##
  pullSecrets: []

## Kubernetes deployment configuration
deployment:

  ## Configure extra options for liveness and readiness probes
  livenessProbe:
    initialDelaySeconds: 300
    periodSeconds: 60
    timeoutSeconds: 5
    failureThreshold: 1
    successThreshold: 1

  ## Configure the ingress resource that allows you to access the service.
  ingress:
    ## enabled sets the ingress record generation or not.
    ##
    ##   Defaults to false.
    ##
    enabled: false

    ## fqdn is the protocol/hostname to be covered with this ingress record.
    ##
    fqdn: "http://doc.local"

    ## path contains the subpath where to access the HTTP service.
    ##
    ##   Defaults to '/'.
    ##
    path: "/"

    ## tls is set to true in order to enable TLS on the ingress record.
    ##
    ##   Defaults to false.
    ##
    tls: false

    ## tlsSecret specifies a secret that contains the key/certificate for TLS
    ##
    tlsSecret: "tls-secret"

    ## annotations contains the Ingress annotations done as key:value pairs
    ##
    annotations: {}

  ## service port
  ##
  ##   Defaults to 8000
  ##
  servicePort: 8000

  ## Configure resource requests and limits
  resources:
    limits:
      memory: "4Gi"
      cpu: "1"
    requests:
      memory: "1Gi"
      cpu: "100m"

  ## Node labels for pod assignment
  ##
  nodeSelector: {}

  ## Tolerations for pod assignment
  ##
  tolerations: []

  ## Affinity for pod assignment
  ##
  affinity: {}
