stages:
  eve-promote:
    worker:
      type: local
    steps:
      - Git:
          name: fetch source
          repourl: "%(prop:git_reference)s"
          method: clobber
          mode: full
          shallow: False
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: check eve_promotion_artifacts property
          command: >
            echo %(prop:eve_promotion_artifacts)s | grep -qE '^[^/]+\:(dev\-|preprod\-|)(staging|prolonged)\-[0-9]+(\.[0-9]+){1,3}\.r[0-9]{12}\.[0-9a-f]+\.[^/]+\.[0-9]+$';
          haltOnFailure: True
      - ShellCommand:
          name: check eve_promotion_tag property
          command: >
            echo %(prop:eve_promotion_tag)s | grep -qE '^[^/\-]+$';
          haltOnFailure: True
      - ShellCommand:
          name: check tag and artifacts consistency
          command: >
            artifacts_commit=`echo %(prop:eve_promotion_artifacts)s | sed -E 's/^[^/]+\:(dev\-|preprod\-|)(staging|prolonged)\-[0-9]+(\.[0-9]+){1,3}\.r[0-9]{12}\.([0-9a-f]+)\.[^/]+\.[0-9]+$/\\4/'`;
            tag_commit=`git rev-list -n 1 %(prop:eve_promotion_tag)s`;
            case ${tag_commit} in
              ${artifacts_commit}*) exit 0;;
              *) exit 1;;
            esac;
          haltOnFailure: True
      - ShellCommand:
          name: promoting
          command: >
            artifacts_prefix=`echo %(prop:eve_promotion_artifacts)s | sed -E 's/(^[^/]+\:)(dev\-|preprod\-|)(staging|prolonged)\-[0-9]+(\.[0-9]+){1,3}\.r[0-9]{12}\.[0-9a-f]+\.[^/]+\.[0-9]+$/\\1\\2/'`;
            artifacts_target=${artifacts_prefix}promoted-%(prop:eve_promotion_tag)s;
            echo "copying '%(prop:eve_promotion_artifacts)s' to '${artifacts_target}'";
            curl --silent http://artifacts/copy/%(prop:eve_promotion_artifacts)s/${artifacts_target}/ | tee /tmp/%(prop:workername)s-promotion-output.log;
          haltOnFailure: True
      - ShellCommand:
          name: check promotion result
          command: >
            tail -1 /tmp/%(prop:workername)s-promotion-output.log | grep -qE '^BUILD COPIED$';
          haltOnFailure: True
  eve-prolong:
    worker:
      type: local
    steps:
      - ShellCommand:
          name: check eve_prolongation_artifacts property
          command: >
            echo %(prop:eve_prolongation_artifacts)s | grep -qE '^[^/]+\:(dev\-|preprod\-|)staging\-[0-9]+(\.[0-9]+){1,3}\.r[0-9]{12}\.[0-9a-f]+\.[^/]+\.[0-9]+$';
          haltOnFailure: True
      - ShellCommand:
          name: prolonging
          command: >
            artifacts_target=`echo %(prop:eve_prolongation_artifacts)s | sed -E 's/(^[^/]+\:)(dev\-|preprod\-|)staging(\-[0-9]+(\.[0-9]+){1,3}\.r[0-9]{12}\.[0-9a-f]+\.[^/]+\.[0-9]+)$/\\1\\2prolonged\\3/'`;
            echo "copying '%(prop:eve_prolongation_artifacts)s' to '${artifacts_target}'";
            curl --silent http://artifacts/copy/%(prop:eve_prolongation_artifacts)s/${artifacts_target}/ | tee /tmp/%(prop:workername)s-prolong-output.log;
          haltOnFailure: True
      - ShellCommand:
          name: check promotion result
          command: >
            tail -1 /tmp/%(prop:workername)s-prolong-output.log | grep -qE '^BUILD COPIED$';
          haltOnFailure: True
