#!/bin/bash

# init
MY_DOCKER_SERVER_INTERNAL_IP=10.176.197.44
MY_DOCKER_SERVER_IP=104.130.169.228
MY_DOCKER_SERVER_HOST=buildfaster.devsca.com


# basic setup
cd /root
curl -fsSL https://get.docker.com/ | sh
curl -fsSL https://get.docker.com/gpg | sudo apt-key add -
# test:
# this should work
docker run hello-world


# remote setup
mkdir docker
cd docker/
openssl genrsa -aes256 -out ca-key.pem 4096
openssl req -new -x509 -days 365 -key ca-key.pem -sha256 -out ca.pem
openssl genrsa -out server-key.pem 4096
openssl req -subj "/CN=${MY_DOCKER_SERVER_HOST}" -sha256 -new -key server-key.pem -out server.csr
echo subjectAltName = IP:${MY_DOCKER_SERVER_IP},IP:${MY_DOCKER_SERVER_INTERNAL_IP},IP:127.0.0.1 > extfile.cnf
openssl x509 -req -days 365 -sha256 -in server.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile extfile.cnf
openssl genrsa -out key.pem 4096
openssl req -subj '/CN=client' -new -key key.pem -out client.csr
echo extendedKeyUsage = clientAuth > extfile2.cnf
openssl x509 -req -days 365 -sha256 -in client.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out cert.pem -extfile extfile2.cnf
chmod -v 0400 *.pem
cat >> /etc/default/docker <<EOF
DOCKER_OPTS="-D --tlsverify --tlscacert=/root/docker/ca.pem --tlscert=/root/docker/server-cert.pem --tlskey=/root/docker/server-key.pem -H=0.0.0.0:2376"
EOF
service docker restart
# test:
# this should fail
docker run hello-world
# this should work
docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=${MY_DOCKER_SERVER_INTERNAL_IP}:2376 run hello-world
# this should work
docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=${MY_DOCKER_SERVER_IP}:2376 run hello-world
# this should work
docker --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=${MY_DOCKER_SERVER_HOST}:2376 run hello-world
