---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" $ }}
  labels:
    app: {{ template "fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "fullname" $ }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" $ }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - name: {{ template "name" $ }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        ports:
        - name: http
          containerPort: {{ .Values.deployment.servicePort }}
        livenessProbe:
          httpGet:
            path: /
            port: http
{{ toYaml .Values.deployment.livenessProbe | indent 10 }}
        resources:
{{ toYaml .Values.deployment.resources | indent 10 }}
        volumeMounts:
        - name: cache
          mountPath: /web/_build
      volumes:
      - name: cache
        emptyDir:
      {{- with .Values.deployment.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end -}}
      {{- with .Values.deployment.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
