apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: crossbar-svc
    name: crossbar-svc
  name: crossbar
  namespace: default
spec:
  ports:
  - name: crossbar
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    k8s-app: crossbar
