---
branches:
  user/*, feature/*, improvement/*, bugfix/*, w/*, q/*:
    stage: static checks

stages:
  static checks:
    worker:
      type: docker
      path: eve/workers/trusty
    steps:
      - Git:
          name: fetch source
          repourl: "%(prop:git_reference)s"
          shallow: True
          retryFetch: True
      - ShellCommand:
          name: run pylint
          command: pylint eve/master tests
      - ShellCommand:
          name: run flake8
          command: flake8 eve/master tests
      - ShellCommand:
          name: run prospector
          command: prospector -F
