---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: eve
    project: {{ env.namespace }}
    service: conf
  name: eve-envvars
data:
  {% for env_var_name, env_var_value in env_vars.items() -%}
  {{ env_var_name }}: "{{ env_var_value }}"
  {% endfor -%}
