{{- if .Values.eve.masterConf.git.gitConfig }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" $ }}-gitconfig
  labels:
    app: {{ template "fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  gitconfig: |
{{ .Values.eve.masterConf.git.gitConfig | indent 4 }}
{{- end }}
