---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" $ }}-files
  labels:
    app: {{ template "fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{- if .Values.eve.masterConf.openstackWorkers.osIdRsa }}
  os_id_rsa: {{ .Values.eve.masterConf.openstackWorkers.osIdRsa | b64enc | quote }}
  {{ end }}
  {{- if .Values.eve.masterConf.dockerWorkers.dockerTlsVerify }}
  ca.pem: {{ .Values.eve.masterConf.dockerWorkers.ca | b64enc | quote }}
  cert.pem: {{ .Values.eve.masterConf.dockerWorkers.cert | b64enc | quote }}
  key.pem: {{ .Values.eve.masterConf.dockerWorkers.key | b64enc | quote }}
  {{- end }}
