---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eve
    project: {{ env.namespace }}
    service: crossbar
  name: crossbar
spec:
  ports:
    - name: crossbar
      port: {{ env.wamp_port }}
      targetPort: {{ env.wamp_port }}
      protocol: TCP
  selector:
    app: eve
    service: crossbar
