---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: eve
    service: doc
  name: doc
spec:
  sessionAffinity: ClientIP
  ports:
    - name: doc
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: eve
    service: doc
