---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" $ }}-frontend
  labels:
    app: {{ template "fullname" $ }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: NodePort
  ports:
  - name: frontend
    port: {{ .Values.deployment.ports.http }}
    targetPort: {{ .Values.deployment.ports.http }}
    protocol: TCP
  selector:
    {{- if gt (.Values.eve.project.mastersCount | int) 1 }}
    app: {{ template "fullname" $ }}-frontend
    {{- else }}
    app: {{ template "fullname" $ }}-master-0
    {{- end }}
