name: publish

on:
  push:
    branches:
      - 'user/**'
      - 'feature/**'
      - 'improvement/**'
      - 'bugfix/**'
      - 'w/**'
      - 'q/**'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - run: sudo apt-get update &&
          DEBIAN_FRONTEND=noninteractive sudo apt-get -y install -q
          apt-transport-https
          build-essential
          curl
          git
          libffi-dev
          libmysqlclient-dev
          libssl-dev
          lsof
          mysql-client
          python3-dev
          python3-pip
          python3-psycopg2
          python3-requests
          telnet
          vim.tiny
      - name: Install dependencies
        run: |
          pip3 install tox tox-gh-actions wheel setuptools==45 setuptools-rust==0.11.6 pip==9.0.1
          pip3 install .
      - name: Test with tox
        run: tox -e docker
      - name: Test with tox
        run: tox -e compose-build
